### ISSUE TITLE
Release version crashing, debug version isn't.

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#55]
Amazing.
Debug version works fine in my emulator, [release version](https://github.com/jariz/Dumpert/releases/download/1.2.0/Dumpert-release.apk) crashes on my phone.
Play version update blocked until this is fixed. :pensive:

**Comment by CytoDev** [comment]
Stacktrace would be nice...

**Comment by jariz** [comment]
Wasn't able to else I would've posted it. But just got it to crash on my emulator
```
   java.lang.ExceptionInInitializerError
       at a.b.b.m.a(Unknown Source)
       at a.b.b.p.<clinit>(Unknown Source)
       at a.b.b.g.<init>(Unknown Source)
       at a.b.b.f.<init>(Unknown Source)
       at a.b.c.di.b(Unknown Source)
       at a.b.c.di.a(Unknown Source)
       at a.b.c.b.a(Unknown Source)
       at a.b.c.ae.a(Unknown Source)
       at a.b.a.a.a(Unknown Source)
       at a.b.a.f.e(Unknown Source)
       at a.b.a.b.a(Unknown Source)
       at io.jari.dumpert.c.a.a(Unknown Source)
       at io.jari.dumpert.c.a.b(Unknown Source)
       at io.jari.dumpert.e.g.run(Unknown Source)
       at java.lang.Thread.run(Thread.java:818)
    Caused by: java.lang.NullPointerException: in == null
       at java.util.Properties.load(Properties.java:246)
       at a.b.b.m.d(Unknown Source)
       at a.b.b.m.<clinit>(Unknown Source)
       at a.b.b.m.a(Unknown Source) 
       at a.b.b.p.<clinit>(Unknown Source) 
       at a.b.b.g.<init>(Unknown Source) 
       at a.b.b.f.<init>(Unknown Source) 
       at a.b.c.di.b(Unknown Source) 
       at a.b.c.di.a(Unknown Source) 
       at a.b.c.b.a(Unknown Source) 
       at a.b.c.ae.a(Unknown Source) 
       at a.b.a.a.a(Unknown Source) 
       at a.b.a.f.e(Unknown Source) 
       at a.b.a.b.a(Unknown Source) 
       at io.jari.dumpert.c.a.a(Unknown Source) 
       at io.jari.dumpert.c.a.b(Unknown Source) 
       at io.jari.dumpert.e.g.run(Unknown Source) 
       at java.lang.Thread.run(Thread.java:818) 
Cannot instantiate class: android.support.v7.widget.SearchView
  java.lang.NoSuchMethodException: <init> [class android.content.Context]
      at java.lang.Class.getConstructor(Class.java:528)
      at java.lang.Class.getConstructor(Class.java:492)
      at android.support.v7.view.k.a(Unknown Source)
      at android.support.v7.view.k.a(Unknown Source)
      at android.support.v7.view.k.b(Unknown Source)
      at android.support.v7.view.i.a(Unknown Source)
      at android.support.v7.view.i.inflate(Unknown Source)
      at io.jari.dumpert.activities.MainActivity.onCreateOptionsMenu(Unknown Source)
      at android.app.Activity.onCreatePanelMenu(Activity.java:2846)
      at android.support.v4.b.u.onCreatePanelMenu(Unknown Source)
      at android.support.v7.view.n.onCreatePanelMenu(Unknown Source)
      at android.support.v7.a.am.onCreatePanelMenu(Unknown Source)
      at android.support.v7.view.n.onCreatePanelMenu(Unknown Source)
      at android.support.v7.a.bj.g(Unknown Source)
      at android.support.v7.a.bk.run(Unknown Source)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at android.os.Looper.loop(Looper.java:148)
      at android.app.ActivityThread.main(ActivityThread.java:5417)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

**Comment by CytoDev** [comment]
and the proguard map would be nice too...

**Comment by jariz** [comment]
Disabling proguard fixes it (?)
I don't know what that is, never used it before. (not sure who turned it on but they clearly didn't test it all that well)
I'll rename this issue and upload the non-proguard version to play for now.

**Comment by CytoDev** [comment]
@jariz, I enabled it. You need to set up exception rules for certain classes.

**Comment by CytoDev** [comment]
@jariz, tried my proposed fix yet? Also, there are a few grammatical errors in the bugfix text on play. (Plus some outdated screenshots)

**Comment by jariz** [comment]
Tablet pics still need to be updated, yes.
Haven't gotten around to it yet, will probably look at it tomorrow.

**Comment by CytoDev** [comment]
@jariz, the possibility exists that your `proguard-android.txt` file has some missing lines compared to mine. (this file can be found in `yourSDK/tools/proguard/` folder).  
  
I'll just paste mine over here for quick reference.  

    # This is a configuration file for ProGuard.
    # http://proguard.sourceforge.net/index.html#manual/usage.html

    -dontusemixedcaseclassnames
    -dontskipnonpubliclibraryclasses
    -verbose

    # Optimization is turned off by default. Dex does not like code run
    # through the ProGuard optimize and preverify steps (and performs some
    # of these optimizations on its own).
    -dontoptimize
    -dontpreverify
    # Note that if you want to enable optimization, you cannot just
    # include optimization flags in your own project configuration file;
    # instead you will need to point to the
    # "proguard-android-optimize.txt" file instead of this one from your
    # project.properties file.

    -keepattributes *Annotation*
    -keep public class com.google.vending.licensing.ILicensingService
    -keep public class com.android.vending.licensing.ILicensingService

    # For native methods, see http://proguard.sourceforge.net/manual/examples.html#native
    -keepclasseswithmembernames class * {
        native <methods>;
    }

    # keep setters in Views so that animations can still work.
    # see http://proguard.sourceforge.net/manual/examples.html#beans
    -keepclassmembers public class * extends android.view.View {
       void set*(***);
       *** get*();
    }

    # We want to keep methods in Activity that could be used in the XML attribute onClick
    -keepclassmembers class * extends android.app.Activity {
       public void *(android.view.View);
    }

    # For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
    -keepclassmembers enum * {
        public static **[] values();
        public static ** valueOf(java.lang.String);
    }

    -keepclassmembers class * implements android.os.Parcelable {
      public static final android.os.Parcelable$Creator CREATOR;
    }

    -keepclassmembers class **.R$* {
        public static <fields>;
    }

    # The support library contains references to newer platform versions.
    # Don't warn about those in case this app is linking against an older
    # platform version.  We know about them, and they are safe.
    -dontwarn android.support.**
