### ISSUE TITLE
Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference [reported error from Play]

### ISSUE THREAD

**Issue by jariz** [jariz/Dumpert#56]
Android: 6.0
Device: Moto X Style (clark)
Application version: latest (1.2.0)
```
java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.view.View.getResources()' on a null object reference
	at android.support.design.widget.Snackbar.make(Snackbar.java:234)
	at io.jari.dumpert.activities.VideoActivity$5.onError(VideoActivity.java:156)
	at android.widget.VideoView$5.onError(VideoView.java:511)
	at android.media.MediaPlayer$EventHandler.handleMessage(MediaPlayer.java:2875)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5443)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
```
[Link to line that causes crash](https://github.com/jariz/Dumpert/blob/81b8fc66406f74fa6ab8bbe0a59262e88c70a5b4/Dumpert/src/main/java/io/jari/dumpert/activities/VideoActivity.java#L156)

**Comment by CytoDev** [comment]
His activity went away as far as I can see. There's little you can do against the garbageman...

**Comment by CytoDev** [comment]
You _can_ query for nullpointers and restore behaviour by reinstating the views, but that would take a lot of trial and error. Your best bet is to let this one slide as a one off, and fix it when you absolutely have to.

**Comment by jariz** [comment]
I figured something like that, just thought I'd post it here because wasn't 100% sure what it meant. Thanks.
